base_url = "https://kyleoneill.dev"

title = "Kyle O'Neill"
description = "The developer portfolio for Kyle O'Neill"
default_language = "en"

compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
[markdown]
[markdown.highlighting]
theme = "slack-dark"
#highlighting = true
#highlight_theme = "agola-dark"

[extra]
author = { name = "Kyle O'Neill" }
